//This is a program that removes line breaks form a user input paragraph.
public class LineBreakRemoval {

	public static void main(String[] args) {
		String s = "HUMAN BEINGS HAVE always\r\n"
				+ "dreamed of flight. They did not,\r\n"
				+ "however, dream of the Boeing 747. The flight to\r\n"
				+ "which humans traditionally aspired was that of\r\n"
				+ "the birds, a business of feathers and flapping\r\n"
				+ "wings. To this the myths and legends of many\r\n"
				+ "cultures testify. In the most famous of these\r\n"
				+ "ancient stories, the skilled craftsman Daedalus\r\n"
				+ "makes wings of feathers and wax so he and his\r\n"
				+ "son Icarus can escape their imprisonment on the\r\n"
				+ "island of Crete. The technology improbably\r\n"
				+ "works, but Icarus flies too close to the sun and\r\n"
				+ "melts the wax, falling to his doom.\r\n"
				+ "The illusion that a person could fly like a bird\r\n"
				+ "or a bat cost some brave and foolish men their\r\n"
				+ "lives or limbs. The historical record is scattered\r\n"
				+ "with “tower jumpers” who launched themselves\r\n"
				+ "into the air supported only by blind faith and\r\n"
				+ "poorly improvised wings. In 1178, for example,\r\n"
				+ "in Constantinople, a follower of Islam chose the\r\n"
				+ "moment of a visit to the Christian Byzantine\r\n"
				+ "Emperor by a Muslim sultan to demonstrate his\r\n"
				+ "powers of flight, jumping off a high building in a\r\n"
				+ "copious white robe stiffened with willow sticks. In\r\n"
				+ "the words of a later flight experimenter, Octave\r\n"
				+ "Chanute, “the weight of his body having more\r\n"
				+ "power to draw him downward than his artificial"
				+ "wings had\r\n"
				+ "to sustain him,\r\n"
				+ "he fell and broke\r\n"
				+ "his bones.” Other\r\n"
				+ "recorded attempts –\r\n"
				+ "by the learned Moor\r\n"
				+ "Abbas ibn-Firnas in\r\n"
				+ "Andalusia in 875, by\r\n"
				+ "English monk Oliver of\r\n"
				+ "Malmesbury in the 11th century,\r\n"
				+ "by Giovanni Battista Danti in\r\n"
				+ "Perugia, Italy, in 1499 – all had the same\r\n"
				+ "result for the same reason.\r\n"
				+ "“Instruments to fly”\r\n"
				+ "Myth and folklore were also rich in tales of\r\n"
				+ "airworthy vehicles that might carry the weight\r\n"
				+ "of a human, from various “chariots of the gods”\r\n"
				+ "to witches’ broomsticks. The idea of a “flying\r\n"
				+ "machine” was picked up by English philosophermonk Roger Bacon in the 13th century – a man\r\n"
				+ "regarded as one of the founders of the modern\r\n"
				+ "scientific tradition. Bacon declared himself certain\r\n"
				+ "that humans could build “instruments to fly,”\r\n"
				+ "involving a mechanism that\r\n"
				+ "would flap wings. Such\r\n"
				+ "“ornithopters” also obsessed\r\n"
				+ "the imagination of Italian\r\n"
				+ "Renaissance genius Leonardo da Vinci.\r\n"
				+ "“There is in man [the ability] to sustain himself\r\n"
				+ "by the flapping of wings,” Leonardo wrote. He\r\n"
				+ "was wrong. In the many sketches of flying\r\n"
				+ "machines found in Leonardo’s notebooks, the\r\n"
				+ "only truly promising idea is a screwlike propeller\r\n"
				+ "that he hoped would spiral into the air – a remote\r\n"
				+"foreshadowing of a helicopter.\r\n"
				+ "If no one could see how to\r\n"
				+ "make a machine that would\r\n"
				+ "fly, they could possibly see why\r\n"
				+ "you would want to – especially in\r\n"
				+ "militaristic Europe, which was divided\r\n"
				+ "into states that were more or less permanently at\r\n"
				+ "war with one another. In 1670, proposing yet\r\n"
				+ "another impractical design – this time for an\r\n"
				+ "airship lifted by spheres from which the air had\r\n"
				+ "been pumped to create a vacuum – Italian Jesuit\r\n"
				+ "Father Francesco de Lana pointed out that such a\r\n"
				+ "vehicle could be used to land troops to capture a\r\n"
				+ "city in a surprise attack, or to destroy houses and\r\n"
				+ "fortresses by dropping \"fireballs and bombs.\"";
		
     // replacing line breaks from string
     s = s.replace("\r\n", " ");
    
     System.out.println(s);

	}

}
